allowed_groups:
  default: ""
  type: list
  list_type: group

vimeo_upload_enabled:
  default: false

vimeo_oauth_client_id:
  default: ""

vimeo_api_access_token:
  default: ""

vimeo_default_view_privacy:
  default: anybody
  type: enum
  choices:
    - anybody
    - unlisted
    - disable

vimeo_default_embed_privacy:
  default: public
  type: enum
  choices:
    - public
    - private

youtube_upload_enabled:
  default: false

youtube_api_client_id:
  default: ""

youtube_default_view_privacy:
  default: unlisted
  type: enum
  choices:
    - private
    - public
    - unlisted

svg_icons:
  default: "fab-youtube|fab-vimeo-v|fa-video"
  type: "list"
  list_type: "compact"

extend_content_security_policy:
  type: list
  default: "script_src: https://accounts.google.com/gsi/client|connect_src: https://api.vimeo.com"
